### PR TITLE
add examples; add Makefile

### LINKED ISSUE #168: TCP connection problem in version 1.2.46
If I'm trying connect to radio via WiFi from python, I'm getting error:

```
    interface = meshtastic.TCPInterface(hostname='192.168.1.28')
AttributeError: module 'meshtastic' has no attribute 'TCPInterface'
```
Everything worked on the previous version 1.2.45

I'm used this method:
`interface = meshtastic.TCPInterface("192.168.1.28")`

Method from manual not working too
`interface = meshtastic.TCPInterface(hostname='192.168.1.28')`

Meshtastic-python ver. 1.2.46

### PR DESCRIPTION
**Pull request by mkinney**
fix #168

### CODE REVIEW

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-python-1-2-48/4614/1
